# CustomTone Configuration

# Model Selection
model:
  # Options: "yue", "musicgen", "magenta"
  type: "musicgen"
  # Model size (small, medium, large)
  size: "medium"
  # Model checkpoint path (leave empty for default)
  checkpoint: ""

# Generation Parameters
generation:
  # Maximum duration in seconds
  max_duration: 30
  # Sample rate
  sample_rate: 44100
  # Temperature for sampling (higher = more random)
  temperature: 0.95
  # Top-k sampling
  top_k: 250
  # Top-p sampling
  top_p: 0.95
  # Classifier-free guidance scale
  cfg_scale: 3.0

# Stem Separation
separation:
  # Options: "demucs", "spleeter"
  model: "demucs"
  # Demucs model version
  demucs_version: "htdemucs_ft"
  # Number of stems (2, 4, 5, or 6)
  num_stems: 4
  # Stem names (depends on num_stems)
  stem_names: ["vocals", "drums", "bass", "other"]

# MIDI Transcription
transcription:
  # Options: "basic_pitch", "onsets_frames"
  model: "basic_pitch"
  # Minimum confidence for note detection
  min_note_confidence: 0.5
  # Minimum duration for notes (seconds)
  min_note_duration: 0.05
  # Save MIDI files
  save_midi: true
  # Save note events as JSON
  save_note_events: false

# Output Settings
output:
  # Base directory for outputs
  base_dir: "outputs"
  # Subdirectories
  dirs:
    full_mix: "full_mix"
    stems: "stems"
    midi: "midi"
    custom_mix: "custom_mix"
  # File formats
  formats:
    audio: "wav"  # Options: "wav", "mp3", "flac"
    midi: "mid"   # Options: "mid", "midi"

# Gradio Interface
gradio:
  # Theme
  theme: "default"
  # Server port
  port: 7860
  # Share publicly
  share: false
  # Maximum queue size
  max_queue_size: 20
  # Authentication (leave empty for no auth)
  auth:
    username: ""
    password: ""
  # Custom CSS
  custom_css: ""

# System Settings
system:
  # Device: "cuda", "cpu", or "auto"
  device: "auto"
  # Number of threads for CPU processing
  num_threads: 4
  # Precision: "fp16" or "fp32"
  precision: "fp16"
  # Cache directory for downloaded models
  cache_dir: "cache"
  # Temporary directory
  temp_dir: "temp"
  # Debug mode
  debug: false
